export const Enum = {
    AnimaDiversionNodeState: {
        Unavailable: 0,
        Available: 1,
        SelectedTemporary: 2,
        SelectedPermanent: 3,
        Cooldown: 4,
    },
    AuctionHouseFilterCategory: {
        Uncategorized: 0,
        Equipment: 1,
        Rarity: 2,
    },
    AuctionStatus: {
        Active: 0,
        Sold: 1,
    },
    ItemCommodityStatus: {
        Unknown: 0,
        Item: 1,
        Commodity: 2,
    },
    AzeritePowerLevel: {
        Base: 0,
        Upgraded: 1,
        Downgraded: 2,
    },
    AzeriteEssence: {
        MainSlot: 0,
        PassiveOneSlot: 1,
        PassiveTwoSlot: 2,
        PassiveThreeSlot: 3,
    },
    ClubActionType: {
        ErrorClubActionSubscribe: 0,
        ErrorClubActionCreate: 1,
        ErrorClubActionEdit: 2,
        ErrorClubActionDestroy: 3,
        ErrorClubActionLeave: 4,
        ErrorClubActionCreateTicket: 5,
        ErrorClubActionDestroyTicket: 6,
        ErrorClubActionRedeemTicket: 7,
        ErrorClubActionGetTicket: 8,
        ErrorClubActionGetTickets: 9,
        ErrorClubActionGetBans: 10,
        ErrorClubActionGetInvitations: 11,
        ErrorClubActionRevokeInvitation: 12,
        ErrorClubActionAcceptInvitation: 13,
        ErrorClubActionDeclineInvitation: 14,
        ErrorClubActionCreateStream: 15,
        ErrorClubActionEditStream: 16,
        ErrorClubActionDestroyStream: 17,
        ErrorClubActionInviteMember: 18,
        ErrorClubActionEditMember: 19,
        ErrorClubActionEditMemberNote: 20,
        ErrorClubActionKickMember: 21,
        ErrorClubActionAddBan: 22,
        ErrorClubActionRemoveBan: 23,
        ErrorClubActionCreateMessage: 24,
        ErrorClubActionEditMessage: 25,
        ErrorClubActionDestroyMessage: 26,
    },
    ClubErrorType: {
        ErrorCommunitiesNone: 0,
        ErrorCommunitiesUnknown: 1,
        ErrorCommunitiesNeutralFaction: 2,
        ErrorCommunitiesUnknownRealm: 3,
        ErrorCommunitiesBadTarget: 4,
        ErrorCommunitiesWrongFaction: 5,
        ErrorCommunitiesRestricted: 6,
        ErrorCommunitiesIgnored: 7,
        ErrorCommunitiesGuild: 8,
        ErrorCommunitiesWrongRegion: 9,
        ErrorCommunitiesUnknownTicket: 10,
        ErrorCommunitiesMissingShortName: 11,
        ErrorCommunitiesProfanity: 12,
        ErrorCommunitiesTrial: 13,
        ErrorCommunitiesVeteranTrial: 14,
        ErrorCommunitiesChatMute: 15,
        ErrorClubFull: 16,
        ErrorClubNoClub: 17,
        ErrorClubNotMember: 18,
        ErrorClubAlreadyMember: 19,
        ErrorClubNoSuchMember: 20,
        ErrorClubNoSuchInvitation: 21,
        ErrorClubInvitationAlreadyExists: 22,
        ErrorClubInvalidRoleID: 23,
        ErrorClubInsufficientPrivileges: 24,
        ErrorClubTooManyClubsJoined: 25,
        ErrorClubVoiceFull: 26,
        ErrorClubStreamNoStream: 27,
        ErrorClubStreamInvalidName: 28,
        ErrorClubStreamCountAtMin: 29,
        ErrorClubStreamCountAtMax: 30,
        ErrorClubMemberHasRequiredRole: 31,
        ErrorClubSentInvitationCountAtMax: 32,
        ErrorClubReceivedInvitationCountAtMax: 33,
        ErrorClubTargetIsBanned: 34,
        ErrorClubBanAlreadyExists: 35,
        ErrorClubBanCountAtMax: 36,
        ErrorClubTicketCountAtMax: 37,
        ErrorClubTicketNoSuchTicket: 38,
        ErrorClubTicketHasConsumedAllowedRedeemCount: 39,
    },
    ClubFieldType: {
        ClubName: 0,
        ClubShortName: 1,
        ClubDescription: 2,
        ClubBroadcast: 3,
        ClubStreamName: 4,
        ClubStreamSubject: 5,
        NumTypes: 6,
    },
    ClubInvitationCandidateStatus: {
        Available: 0,
        InvitePending: 1,
        AlreadyMember: 2,
    },
    ClubMemberPresence: {
        Unknown: 0,
        Online: 1,
        OnlineMobile: 2,
        Offline: 3,
        Away: 4,
        Busy: 5,
    },
    ClubRemovedReason: {
        None: 0,
        Banned: 1,
        Removed: 2,
        ClubDestroyed: 3,
    },
    ClubRestrictionReason: {
        None: 0,
        Unavailable: 1,
    },
    ClubRoleIdentifier: {
        Owner: 1,
        Leader: 2,
        Moderator: 3,
        Member: 4,
    },
    ClubStreamNotificationFilter: {
        None: 0,
        Mention: 1,
        All: 2,
    },
    ClubStreamType: {
        General: 0,
        Guild: 1,
        Officer: 2,
        Other: 3,
    },
    ClubType: {
        BattleNet: 0,
        Character: 1,
        Guild: 2,
        Other: 3,
    },
    ValidateNameResult: {
        NameSuccess: 0,
        NameFailure: 1,
        NameNoName: 2,
        NameTooShort: 3,
        NameTooLong: 4,
        NameInvalidCharacter: 5,
        NameMixedLanguages: 6,
        NameProfane: 7,
        NameReserved: 8,
        NameInvalidApostrophe: 9,
        NameMultipleApostrophes: 10,
        NameThreeConsecutive: 11,
        NameInvalidSpace: 12,
        NameConsecutiveSpaces: 13,
        NameRussianConsecutiveSilentCharacters: 14,
        NameRussianSilentCharacterAtBeginningOrEnd: 15,
        NameDeclensionDoesntMatchBaseName: 16,
        NameSpacesDisallowed: 17,
    },
    ClubFinderApplicationUpdateType: {
        None: 0,
        AcceptInvite: 1,
        DeclineInvite: 2,
        Cancel: 3,
    },
    ClubFinderClubPostingStatusFlags: {
        None: 0,
        NeedsCacheUpdate: 1,
        ForceDescriptionChange: 2,
        ForceNameChange: 3,
        UnderReview: 4,
        Banned: 5,
        FakePost: 6,
        PendingDelete: 7,
        PostDelisted: 8,
    },
    ClubFinderDisableReason: {
        Muted: 0,
        Silenced: 1,
        VeteranTrial: 2,
    },
    ClubFinderPostingReportType: {
        PostersName: 0,
        ClubName: 1,
        PostingDescription: 2,
        ApplicantsName: 3,
        JoinNote: 4,
    },
    ClubFinderRequestType: {
        None: 0,
        Guild: 1,
        Community: 2,
        All: 3,
    },
    ClubFinderSettingFlags: {
        None: 0,
        Dungeons: 1,
        Raids: 2,
        PvP: 3,
        RP: 4,
        Social: 5,
        Small: 6,
        Medium: 7,
        Large: 8,
        Tank: 9,
        Healer: 10,
        Damage: 11,
        EnableListing: 12,
        MaxLevelOnly: 13,
        AutoAccept: 14,
        FactionHorde: 15,
        FactionAlliance: 16,
        FactionNeutral: 17,
        SortRelevance: 18,
        SortMemberCount: 19,
        SortNewest: 20,
        LanguageReserved1: 21,
        LanguageReserved2: 22,
        LanguageReserved3: 23,
        LanguageReserved4: 24,
        LanguageReserved5: 25,
    },
    PlayerClubRequestStatus: {
        None: 0,
        Pending: 1,
        AutoApproved: 2,
        Declined: 3,
        Approved: 4,
        Joined: 5,
        JoinedAnother: 6,
        Canceled: 7,
    },
    TrackedSpellCategory: {
        Offensive: 0,
        Defensive: 1,
        Debuff: 2,
        Count: 3,
    },
    ConfigurationWarning: {
        ShaderModelWillBeOutdated: 0,
        ShaderModelIsOutdated: 1,
        ConsoleDeviceSseOutdated: 2,
        DriverBlacklisted: 3,
        DriverOutOfDate: 4,
        DeviceBlacklisted: 5,
        GraphicsApiWillBeOutdated: 6,
        OsBitsWillBeOutdated: 7,
    },
    ConsoleCategory: {
        Debug: 0,
        Graphics: 1,
        Console: 2,
        Combat: 3,
        Game: 4,
        Default: 5,
        Net: 6,
        Sound: 7,
        Gm: 8,
        Reveal: 9,
        None: 10,
    },
    ConsoleColorType: {
        DefaultColor: 0,
        InputColor: 1,
        EchoColor: 2,
        ErrorColor: 3,
        WarningColor: 4,
        GlobalColor: 5,
        AdminColor: 6,
        HighlightColor: 7,
        BackgroundColor: 8,
        ClickbufferColor: 9,
        PrivateColor: 10,
        DefaultGreen: 11,
    },
    ConsoleCommandType: {
        Cvar: 0,
        Command: 1,
        Script: 2,
    },
    ContributionAppearanceFlags: {
        TooltipUseTimeRemaining: 0,
    },
    ContributionResult: {
        Success: 0,
        MustBeNearNpc: 1,
        IncorrectState: 2,
        InvalidID: 3,
        QuestDataMissing: 4,
        FailedConditionCheck: 5,
        UnableToCompleteTurnIn: 6,
        InternalError: 7,
    },
    ContributionState: {
        None: 0,
        Building: 1,
        Active: 2,
        UnderAttack: 3,
        Destroyed: 4,
    },
    CovenantAbilityType: {
        Class: 0,
        Signature: 1,
        Soulbind: 2,
    },
    UICursorType: {
        Default: 0,
        Item: 1,
        Money: 2,
        Spell: 3,
        PetAction: 4,
        Merchant: 5,
        ActionBar: 6,
        Macro: 7,
        AmmoObsolete: 8,
        Pet: 9,
        GuildBank: 10,
        GuildBankMoney: 11,
        EquipmentSet: 12,
        Currency: 13,
        Flyout: 14,
        VoidItem: 15,
        BattlePet: 16,
        Mount: 17,
        Toy: 18,
        CommunitiesStream: 19,
        ConduitCollectionItem: 20,
    },
    SelfResurrectOptionType: {
        Spell: 0,
        Item: 1,
    },
    ItemSlotFilterType: {
        Head: 0,
        Neck: 1,
        Shoulder: 2,
        Cloak: 3,
        Chest: 4,
        Wrist: 5,
        Hand: 6,
        Waist: 7,
        Legs: 8,
        Feet: 9,
        MainHand: 10,
        OffHand: 11,
        Finger: 12,
        Trinket: 13,
        Other: 14,
        NoFilter: 15,
    },
    SubscriptionInterstitialResponseType: {
        Clicked: 0,
        Closed: 1,
        WebRedirect: 2,
    },
    SubscriptionInterstitialType: {
        Standard: 0,
        LeftNpeArea: 1,
        MaxLevel: 2,
    },
    GossipOptionRewardType: {
        Item: 0,
        Currency: 1,
    },
    GossipOptionStatus: {
        Available: 0,
        Unavailable: 1,
        Locked: 2,
        AlreadyComplete: 3,
    },
    NavigationState: {
        Invalid: 0,
        Occluded: 1,
        InRange: 2,
    },
    SummonStatus: {
        None: 0,
        Pending: 1,
        Accepted: 2,
        Declined: 3,
    },
    ItemInteractionFrameType: {
        CleanseCorruption: 0,
    },
    CustomBindingType: {
        VoicePushToTalk: 0,
    },
    MapCanvasPosition: {
        None: 0,
        BottomLeft: 1,
        BottomRight: 2,
        TopLeft: 3,
        TopRight: 4,
    },
    UIMapFlag: {
        NoHighlight: 1,
        ShowOverlays: 2,
        ShowTaxiNodes: 4,
        GarrisonMap: 8,
        FallbackToParentMap: 16,
        NoHighlightTexture: 32,
        ShowTaskObjectives: 64,
        NoWorldPositions: 128,
        HideArchaeologyDigs: 256,
        Deprecated: 512,
        HideIcons: 1024,
        HideVignettes: 2048,
        ForceAllOverlayExplored: 4096,
        FlightMapShowZoomOut: 8192,
        FlightMapAutoZoom: 16384,
        ForceOnNavbar: 32768,
    },
    UIMapSystem: {
        World: 0,
        Taxi: 1,
        Adventure: 2,
        Minimap: 3,
    },
    UIMapType: {
        Cosmic: 0,
        World: 1,
        Continent: 2,
        Zone: 3,
        Dungeon: 4,
        Micro: 5,
        Orphan: 6,
    },
    PartyRequestJoinRelation: {
        None: 0,
        Friend: 1,
        Guild: 2,
        Club: 3,
        NumPartyRequestJoinRelations: 4,
    },
    PetJournalError: {
        None: 0,
        PetIsDead: 1,
        JournalIsLocked: 2,
        InvalidFaction: 3,
        NoFavoritesToSummon: 4,
        NoValidRandomSummon: 5,
        InvalidCovenant: 6,
    },
    PlayerChoiceRarity: {
        Common: 0,
        Uncommon: 1,
        Rare: 2,
        Epic: 3,
    },
    BrawlType: {
        None: 0,
        Battleground: 1,
        Arena: 2,
        Lfg: 3,
    },
    PvPMatchState: {
        Inactive: 0,
        Active: 1,
        Complete: 2,
    },
    QuestLineFloorLocation: {
        Above: 0,
        Below: 1,
        Same: 2,
    },
    MapOverlayDisplayLocation: {
        Default: 0,
        BottomLeft: 1,
        TopLeft: 2,
        BottomRight: 3,
        TopRight: 4,
        Hidden: 5,
    },
    QuestFrequency: {
        Default: 0,
        Daily: 1,
        Weekly: 2,
    },
    QuestTag: {
        Group: 1,
        PvP: 41,
        Raid: 62,
        Dungeon: 81,
        Legendary: 83,
        Heroic: 85,
        Raid10: 88,
        Raid25: 89,
        Scenario: 98,
        Account: 102,
        CombatAlly: 266,
    },
    QuestWatchType: {
        Automatic: 0,
        Manual: 1,
    },
    WorldQuestQuality: {
        Common: 0,
        Rare: 1,
        Epic: 2,
    },
    RafRecruitActivityState: {
        Incomplete: 0,
        Complete: 1,
        RewardClaimed: 2,
    },
    RafRecruitSubStatus: {
        Trial: 0,
        Active: 1,
        Inactive: 2,
    },
    RafRewardType: {
        Pet: 0,
        Mount: 1,
        Appearance: 2,
        Title: 3,
        GameTime: 4,
        AppearanceSet: 5,
        Illusion: 6,
        Invalid: 7,
    },
    JailersTowerType: {
        TwistingCorridors: 0,
        SkoldusHalls: 1,
        FractureChambers: 2,
        Soulforges: 3,
        Coldheart: 4,
        Mortregar: 5,
        UpperReaches: 6,
        ArkobanHall: 7,
        TormentChamberJaina: 8,
        TormentChamberThrall: 9,
        TormentChamberAnduin: 10,
    },
    ScriptedAnimationBehavior: {
        None: 0,
        TargetShake: 1,
        TargetKnockBack: 2,
        SourceRecoil: 3,
        SourceCollideWithTarget: 4,
        UIParentShake: 5,
    },
    ScriptedAnimationTrajectory: {
        AtSource: 0,
        AtTarget: 1,
        Straight: 2,
        CurveLeft: 3,
        CurveRight: 4,
        CurveRandom: 5,
        HalfwayBetween: 6,
    },
    SplashScreenType: {
        WhatsNew: 0,
        SeasonRollOver: 1,
    },
    FlightPathFaction: {
        Neutral: 0,
        Horde: 1,
        Alliance: 2,
    },
    FlightPathState: {
        Current: 0,
        Reachable: 1,
        Unreachable: 2,
    },
    TooltipSide: {
        Left: 0,
        Right: 1,
        Top: 2,
        Bottom: 3,
    },
    TooltipTextureAnchor: {
        LeftTop: 0,
        LeftCenter: 1,
        LeftBottom: 2,
        RightTop: 3,
        RightCenter: 4,
        RightBottom: 5,
        All: 6,
    },
    TooltipTextureRelativeRegion: {
        LeftLine: 0,
        RightLine: 1,
    },
    OptionalReagentItemFlag: {
        TooltipShowsAsStatModifications: 0,
    },
    TransmogCollectionType: {
        Head: 0,
        Shoulder: 1,
        Back: 2,
        Chest: 3,
        Shirt: 4,
        Tabard: 5,
        Wrist: 6,
        Hands: 7,
        Waist: 8,
        Legs: 9,
        Feet: 10,
        Wand: 11,
        OneHAxe: 12,
        OneHSword: 13,
        OneHMace: 14,
        Dagger: 15,
        Fist: 16,
        Shield: 17,
        Holdable: 18,
        TwoHAxe: 19,
        TwoHSword: 20,
        TwoHMace: 21,
        Staff: 22,
        Polearm: 23,
        Bow: 24,
        Gun: 25,
        Crossbow: 26,
        Warglaives: 27,
        Paired: 28,
    },
    TransmogModification: {
        None: 0,
        RightShoulder: 1,
    },
    TransmogSource: {
        None: 0,
        JournalEncounter: 1,
        Quest: 2,
        Vendor: 3,
        WorldDrop: 4,
        HiddenUntilCollected: 5,
        CantCollect: 6,
        Achievement: 7,
        Profession: 8,
        NotValidForTransmog: 9,
    },
    TransmogType: {
        Appearance: 0,
        Illusion: 1,
    },
    ItemTryOnReason: {
        Success: 0,
        WrongRace: 1,
        NotEquippable: 2,
        DataPending: 3,
    },
    ModelSceneSetting: {
        AlignLightToOrbitDelta: 1,
    },
    ModelSceneType: {
        MountJournal: 0,
        PetJournalCard: 1,
        ShopCard: 2,
        EncounterJournal: 3,
        PetJournalLoadout: 4,
        ArtifactTier2: 5,
        ArtifactTier2ForgingScene: 6,
        ArtifactTier2SlamEffect: 7,
        CommentatorVictoryFanfare: 8,
        ArtifactRelicTalentEffect: 9,
        PvPWarModeOrb: 10,
        PvPWarModeFire: 11,
        PartyPose: 12,
        AzeriteItemLevelUpToast: 13,
        AzeritePowers: 14,
        AzeriteRewardGlow: 15,
        HeartOfAzeroth: 16,
        WorldMapThreat: 17,
        Soulbinds: 18,
        JailersTowerAnimaGlow: 19,
    },
    CaptureBarWidgetFillDirectionType: {
        RightToLeft: 0,
        LeftToRight: 1,
    },
    CaptureBarWidgetGlowAnimType: {
        None: 0,
        Pulse: 1,
    },
    IconAndTextWidgetState: {
        Hidden: 0,
        Shown: 1,
        ShownWithDynamicIconFlashing: 2,
        ShownWithDynamicIconNotFlashing: 3,
    },
    IconState: {
        Hidden: 0,
        ShowState1: 1,
        ShowState2: 2,
    },
    SpellDisplayIconDisplayType: {
        Buff: 0,
        Debuff: 1,
        Circular: 2,
    },
    SpellDisplayIconSizeType: {
        Small: 0,
        Medium: 1,
        Large: 2,
    },
    SpellDisplayTextShownStateType: {
        Shown: 0,
        Hidden: 1,
    },
    StatusBarColorTintValue: {
        None: 0,
        Black: 1,
        White: 2,
        Red: 3,
        Yellow: 4,
        Orange: 5,
        Purple: 6,
        Green: 7,
        Blue: 8,
    },
    StatusBarOverrideBarTextShownType: {
        Never: 0,
        Always: 1,
        OnlyOnMouseover: 2,
        OnlyNotOnMouseover: 3,
    },
    StatusBarValueTextType: {
        Hidden: 0,
        Percentage: 1,
        Value: 2,
        Time: 3,
        TimeShowOneLevelOnly: 4,
        ValueOverMax: 5,
        ValueOverMaxNormalized: 6,
    },
    UIWidgetFlag: {
        UniversalWidget: 1,
    },
    UIWidgetFontType: {
        Normal: 0,
        Shadow: 1,
        Outline: 2,
    },
    UIWidgetTextSizeType: {
        Small: 0,
        Medium: 1,
        Large: 2,
        Huge: 3,
    },
    WidgetAnimationType: {
        None: 0,
        Fade: 1,
    },
    WidgetCurrencyClass: {
        Currency: 0,
        Item: 1,
    },
    WidgetEnabledState: {
        Disabled: 0,
        Enabled: 1,
        Red: 2,
        Highlight: 3,
    },
    WidgetShownState: {
        Hidden: 0,
        Shown: 1,
    },
    ZoneControlActiveState: {
        Inactive: 0,
        Active: 1,
    },
    ZoneControlDangerFlashType: {
        ShowOnGoodStates: 0,
        ShowOnBadStates: 1,
        ShowOnBoth: 2,
        ShowOnNeither: 3,
    },
    ZoneControlFillType: {
        SingleFillClockwise: 0,
        SingleFillCounterClockwise: 1,
        DoubleFillClockwise: 2,
        DoubleFillCounterClockwise: 3,
    },
    ZoneControlLeadingEdgeType: {
        NoLeadingEdge: 0,
        UseLeadingEdge: 1,
    },
    ZoneControlMode: {
        BothStatesAreGood: 0,
        State1IsGood: 1,
        State2IsGood: 2,
        NeitherStateIsGood: 3,
    },
    ZoneControlState: {
        State1: 0,
        State2: 1,
    },
    PhaseReason: {
        Phasing: 0,
        Sharding: 1,
        WarMode: 2,
        ChromieTime: 3,
    },
    PowerType: {
        HealthCost: -2,
        None: -1,
        Mana: 0,
        Rage: 1,
        Focus: 2,
        Energy: 3,
        ComboPoints: 4,
        Runes: 5,
        RunicPower: 6,
        SoulShards: 7,
        LunarPower: 8,
        HolyPower: 9,
        Alternate: 10,
        Maelstrom: 11,
        Chi: 12,
        Insanity: 13,
        Obsolete: 14,
        Obsolete2: 15,
        ArcaneCharges: 16,
        Fury: 17,
        Pain: 18,
        NumPowerTypes: 19,
    },
    PvPUnitClassification: {
        FlagCarrierHorde: 0,
        FlagCarrierAlliance: 1,
        FlagCarrierNeutral: 2,
        CartRunnerHorde: 3,
        CartRunnerAlliance: 4,
        AssassinHorde: 5,
        AssassinAlliance: 6,
        OrbCarrierBlue: 7,
        OrbCarrierGreen: 8,
        OrbCarrierOrange: 9,
        OrbCarrierPurple: 10,
    },
    VignetteType: {
        Normal: 0,
        PvPBounty: 1,
        Torghast: 2,
        Treasure: 3,
    },
    CommunicationMode: {
        PushToTalk: 0,
        OpenMic: 1,
    },
    VoiceChannelErrorReason: {
        Unknown: 0,
        IsBattleNetChannel: 1,
    },
    VoiceChatStatusCode: {
        Success: 0,
        OperationPending: 1,
        TooManyRequests: 2,
        LoginProhibited: 3,
        ClientNotInitialized: 4,
        ClientNotLoggedIn: 5,
        ClientAlreadyLoggedIn: 6,
        ChannelNameTooShort: 7,
        ChannelNameTooLong: 8,
        ChannelAlreadyExists: 9,
        AlreadyInChannel: 10,
        TargetNotFound: 11,
        Failure: 12,
        ServiceLost: 13,
        UnableToLaunchProxy: 14,
        ProxyConnectionTimeOut: 15,
        ProxyConnectionUnableToConnect: 16,
        ProxyConnectionUnexpectedDisconnect: 17,
        Disabled: 18,
        UnsupportedChatChannelType: 19,
        InvalidCommunityStream: 20,
        PlayerSilenced: 21,
        PlayerVoiceChatParentalDisabled: 22,
        InvalidInputDevice: 23,
        InvalidOutputDevice: 24,
    },
    CampaignState: {
        Invalid: 0,
        Complete: 1,
        InProgress: 2,
        Stalled: 3,
    },
    ConquestProgressBarDisplayType: {
        FirstChest: 0,
        AdditionalChest: 1,
        Seasonal: 2,
    },
    WoWEntitlementType: {
        Item: 0,
        Mount: 1,
        Battlepet: 2,
        Toy: 3,
        Appearance: 4,
        AppearanceSet: 5,
        GameTime: 6,
        Title: 7,
        Illusion: 8,
        Invalid: 9,
    },
    AuctionHouseCommoditySortOrder: {
        UnitPrice: 0,
        Quantity: 1,
    },
    AuctionHouseFilter: {
        UncollectedOnly: 0,
        UsableOnly: 1,
        UpgradesOnly: 2,
        ExactMatch: 3,
        PoorQuality: 4,
        CommonQuality: 5,
        UncommonQuality: 6,
        RareQuality: 7,
        EpicQuality: 8,
        LegendaryQuality: 9,
        ArtifactQuality: 10,
        LegendaryCraftedItemOnly: 11,
    },
    AuctionHouseItemSortOrder: {
        Bid: 0,
        Buyout: 1,
    },
    AuctionHouseSortOrder: {
        Price: 0,
        Name: 1,
        Level: 2,
        Bid: 3,
        Buyout: 4,
        TimeRemaining: 5,
    },
    AuctionHouseTimeLeftBand: {
        Short: 0,
        Medium: 1,
        Long: 2,
        VeryLong: 3,
    },
    CalendarCommandType: {
        CalendarCommandCreate: 0,
        CalendarCommandInvite: 1,
        CalendarCommandRsvp: 2,
        CalendarCommandRemoveInvite: 3,
        CalendarCommandRemoveEvent: 4,
        CalendarCommandStatus: 5,
        CalendarCommandModeratorStatus: 6,
        CalendarCommandGetCalendar: 7,
        CalendarCommandGetEvent: 8,
        CalendarCommandUpdateEvent: 9,
        CalendarCommandComplain: 10,
        CalendarCommandNotes: 11,
    },
    CalendarErrorType: {
        CalendarErrorSuccess: 0,
        CalendarErrorCommunityEventsExceeded: 1,
        CalendarErrorEventsExceeded: 2,
        CalendarErrorSelfInvitesExceeded: 3,
        CalendarErrorOtherInvitesExceeded: 4,
        CalendarErrorNoPermission: 5,
        CalendarErrorEventInvalid: 6,
        CalendarErrorNotInvited: 7,
        CalendarErrorUnknownError: 8,
        CalendarErrorNotInGuild: 9,
        CalendarErrorNotInCommunity: 10,
        CalendarErrorTargetAlreadyInvited: 11,
        CalendarErrorNameNotFound: 12,
        CalendarErrorWrongFaction: 13,
        CalendarErrorIgnored: 14,
        CalendarErrorInvitesExceeded: 15,
        CalendarErrorInvalidMaxSize: 16,
        CalendarErrorInvalidDate: 17,
        CalendarErrorInvalidTime: 18,
        CalendarErrorNoInvites: 19,
        CalendarErrorNeedsTitle: 20,
        CalendarErrorEventPassed: 21,
        CalendarErrorEventLocked: 22,
        CalendarErrorDeleteCreatorFailed: 23,
        CalendarErrorDataAlreadySet: 24,
        CalendarErrorCalendarDisabled: 25,
        CalendarErrorRestrictedAccount: 26,
        CalendarErrorArenaEventsExceeded: 27,
        CalendarErrorRestrictedLevel: 28,
        CalendarErrorSquelched: 29,
        CalendarErrorNoInvite: 30,
        CalendarErrorComplaintDisabled: 31,
        CalendarErrorComplaintSelf: 32,
        CalendarErrorComplaintSameGuild: 33,
        CalendarErrorComplaintGm: 34,
        CalendarErrorComplaintLimit: 35,
        CalendarErrorComplaintNotFound: 36,
        CalendarErrorEventWrongServer: 37,
        CalendarErrorNoCommunityInvites: 38,
        CalendarErrorInvalidSignup: 39,
        CalendarErrorNoModerator: 40,
        CalendarErrorModeratorRestricted: 41,
        CalendarErrorInvalidNotes: 42,
        CalendarErrorInvalidTitle: 43,
        CalendarErrorInvalidDescription: 44,
        CalendarErrorInvalidClub: 45,
        CalendarErrorCreatorNotFound: 46,
        CalendarErrorEventThrottled: 47,
        CalendarErrorInviteThrottled: 48,
        CalendarErrorInternal: 49,
        CalendarErrorComplaintAdded: 50,
    },
    CalendarEventBits: {
        CalendarEventBitPlayer: 1,
        CalendarEventBitGuildDeprecated: 2,
        CalendarEventBitSystem: 4,
        CalendarEventBitHoliday: 8,
        CalendarEventBitLocked: 16,
        CalendarEventBitAutoApprove: 32,
        CalendarEventBitCommunityAnnouncement: 64,
        CalendarEventBitRaidLockout: 128,
        CalendarEventBitArenaDeprecated: 256,
        CalendarEventBitRaidResetDeprecated: 512,
        CalendarEventBitCommunitySignup: 1024,
        CalendarEventBitGuildSignup: 2048,
        CommunityWide: 3136,
        PlayerCreated: 3395,
        CantComplain: 3788,
    },
    CalendarEventRepeatOptions: {
        CalendarRepeatNever: 0,
        CalendarRepeatWeekly: 1,
        CalendarRepeatBiweekly: 2,
        CalendarRepeatMonthly: 3,
    },
    CalendarEventType: {
        Raid: 0,
        Dungeon: 1,
        PvP: 2,
        Meeting: 3,
        Other: 4,
        HeroicDeprecated: 5,
    },
    CalendarFilterFlags: {
        WeeklyHoliday: 1,
        Darkmoon: 2,
        Battleground: 4,
        RaidLockout: 8,
        RaidReset: 16,
    },
    CalendarGetEventType: {
        Get: 0,
        Add: 1,
        Copy: 2,
        DefaultCalendarGetEventType: 0,
    },
    CalendarHolidayFilterType: {
        Weekly: 0,
        Darkmoon: 1,
        Battleground: 2,
    },
    CalendarInviteBits: {
        CalendarInviteBitPendingInvite: 1,
        CalendarInviteBitModerator: 2,
        CalendarInviteBitCreator: 4,
        CalendarInviteBitSignup: 8,
    },
    CalendarInviteSortType: {
        CalendarInviteSortName: 0,
        CalendarInviteSortLevel: 1,
        CalendarInviteSortClass: 2,
        CalendarInviteSortStatus: 3,
        CalendarInviteSortParty: 4,
        CalendarInviteSortNotes: 5,
    },
    CalendarInviteType: {
        Normal: 0,
        Signup: 1,
    },
    CalendarModeratorStatus: {
        CalendarModeratorNone: 0,
        CalendarModeratorModerator: 1,
        CalendarModeratorCreator: 2,
    },
    CalendarStatus: {
        Invited: 0,
        Available: 1,
        Declined: 2,
        Confirmed: 3,
        Out: 4,
        Standby: 5,
        Signedup: 6,
        NotSignedup: 7,
        Tentative: 8,
    },
    CalendarType: {
        Player: 0,
        Community: 1,
        RaidLockout: 2,
        RaidResetDeprecated: 3,
        Holiday: 4,
        HolidayWeekly: 5,
        HolidayDarkmoon: 6,
        HolidayBattleground: 7,
    },
    CalendarWebActionType: {
        Accept: 0,
        Decline: 1,
        Remove: 2,
        ReportSpam: 3,
        Signup: 4,
        Tentative: 5,
        TentativeSignup: 6,
    },
    HolidayCalendarFlags: {
        Alliance: 1,
        Horde: 2,
    },
    HolidayFlags: {
        IsRegionwide: 1,
        DontShowInCalendar: 2,
        DontDisplayEnd: 4,
        DontDisplayBanner: 8,
        NotAvailableClientSide: 16,
    },
    ChrCustomizationCategoryFlag: {
        UndressModel: 1,
    },
    ChrCustomizationOptionType: {
        SelectionPopout: 0,
        Checkbox: 1,
        Slider: 2,
    },
    Unitsex: {
        Male: 0,
        Female: 1,
        None: 2,
    },
    ChatChannelRuleset: {
        None: 0,
        Mentor: 1,
        Disabled: 2,
    },
    ChatChannelType: {
        None: 0,
        Custom: 1,
        PrivateParty: 2,
        PublicParty: 3,
        Communities: 4,
    },
    CallingStates: {
        QuestOffer: 0,
        QuestActive: 1,
        QuestCompleted: 2,
    },
    CurrencyDestroyReason: {
        Cheat: 0,
        Spell: 1,
        VersionUpdate: 2,
        QuestTurnin: 3,
        Vendor: 4,
        Trade: 5,
        Capped: 6,
        Garrison: 7,
        DroppedToCorpse: 8,
        BonusRoll: 9,
        FactionConversion: 10,
        Last: 11,
    },
    CurrencyFlags: {
        CurrencyTradable: 1,
        CurrencyAppearsInLootWindow: 2,
        CurrencyComputedWeeklyMaximum: 4,
        Currency_100_Scaler: 8,
        CurrencyNoLowLevelDrop: 16,
        CurrencyIgnoreMaxQtyOnLoad: 32,
        CurrencyLogOnWorldChange: 64,
        CurrencyTrackQuantity: 128,
        CurrencyResetTrackedQuantity: 256,
        CurrencyUpdateVersionIgnoreMax: 512,
        CurrencySuppressChatMessageOnVersionChange: 1024,
        CurrencySingleDropInLoot: 2048,
        CurrencyHasWeeklyCatchup: 4096,
        CurrencyDoNotCompressChat: 8192,
        CurrencyDoNotLogAcquisitionToBi: 16384,
        CurrencyNoRaidDrop: 32768,
        CurrencyNotPersistent: 65536,
        CurrencyDeprecated: 131072,
        CurrencyDynamicMaximum: 262144,
        CurrencySuppressChatMessages: 524288,
        CurrencyDoNotToast: 1048576,
        CurrencyDestroyExtraOnLoot: 2097152,
        CurrencyDontShowTotalInTooltip: 4194304,
        CurrencyDontCoalesceInLootWindow: 8388608,
        CurrencyAccountWide: 16777216,
        CurrencyAllowOverflowMailer: 33554432,
        CurrencyHideAsReward: 67108864,
        CurrencyHasWarmodeBonus: 134217728,
        CurrencyIsAllianceOnly: 268435456,
        CurrencyIsHordeOnly: 536870912,
        CurrencyLimitWarmodeBonusOncePerTooltip: 1073741824,
        DeprecatedCurrencyFlag: -2147483648,
    },
    CurrencyFlagsB: {
        CurrencyBUseTotalEarnedForMaxQty: 1,
        CurrencyBShowQuestXpGainInTooltip: 2,
    },
    CurrencyGainFlags: {
        BonusAward: 1,
        DroppedFromDeath: 2,
        FromAccountServer: 4,
    },
    CurrencySource: {
        ConvertOldItem: 0,
        ConvertOldPvPCurrency: 1,
        ItemRefund: 2,
        QuestReward: 3,
        Cheat: 4,
        Vendor: 5,
        PvPKillCredit: 6,
        PvPMetaCredit: 7,
        PvPScriptedAward: 8,
        Loot: 9,
        UpdatingVersion: 10,
        LfgReward: 11,
        Trade: 12,
        Spell: 13,
        ItemDeletion: 14,
        RatedBattleground: 15,
        RandomBattleground: 16,
        Arena: 17,
        ExceededMaxQty: 18,
        PvPCompletionBonus: 19,
        Script: 20,
        GuildBankWithdrawal: 21,
        Pushloot: 22,
        GarrisonBuilding: 23,
        PvPDrop: 24,
        GarrisonFollowerActivation: 25,
        GarrisonBuildingRefund: 26,
        GarrisonMissionReward: 27,
        GarrisonResourceOverTime: 28,
        QuestRewardIgnoreCaps: 29,
        GarrisonTalent: 30,
        GarrisonWorldQuestBonus: 31,
        PvPHonorReward: 32,
        BonusRoll: 33,
        AzeriteRespec: 34,
        WorldQuestReward: 35,
        WorldQuestRewardIgnoreCaps: 36,
        FactionConversion: 37,
        DailyQuestReward: 38,
        DailyQuestWarModeReward: 39,
        WeeklyQuestReward: 40,
        WeeklyQuestWarModeReward: 41,
        AccountCopy: 42,
        WeeklyRewardChest: 43,
        GarrisonTalentTreeReset: 44,
        Last: 45,
    },
    CurrencyTokenCategoryFlags: {
        FlagSortLast: 1,
        FlagPlayerItemAssignment: 2,
        Hidden: 4,
        Virtual: 8,
    },
    PlayerCurrencyFlags: {
        Incremented: 1,
        Loading: 2,
    },
    PlayerCurrencyFlagsDbFlags: {
        IgnoreMaxQtyOnload: 1,
        Reuse1: 2,
        InBackpack: 4,
        UnusedInUI: 8,
        Reuse2: 16,
    },
    Damageclass: {
        Physical: 0,
        Holy: 1,
        Fire: 2,
        Nature: 3,
        Frost: 4,
        Shadow: 5,
        Arcane: 6,
        FirstResist: 2,
        LastResist: 6,
        MaskPhysical: 1,
        MaskHoly: 2,
        MaskFire: 4,
        MaskNature: 8,
        MaskFrost: 16,
        MaskShadow: 32,
        MaskArcane: 64,
        AllPhysical: 1,
        AllMagical: 126,
        All: 127,
        MaskFlamestrike: 5,
        MaskFroststrike: 17,
        MaskSpellstrike: 65,
        MaskShadowstrike: 33,
        MaskStormstrike: 9,
        MaskHolystrike: 3,
        MaskFrostfire: 20,
        MaskSpellfire: 68,
        MaskFirestorm: 12,
        MaskShadowflame: 36,
        MaskHolyfire: 6,
        MaskSpellfrost: 80,
        MaskFroststorm: 24,
        MaskShadowfrost: 48,
        MaskHolyfrost: 18,
        MaskSpellstorm: 72,
        MaskSpellshadow: 96,
        MaskDivine: 66,
        MaskShadowstorm: 40,
        MaskHolystorm: 10,
        MaskTwilight: 34,
        MaskElemental: 28,
        MaskChromatic: 62,
        MaskMagical: 126,
        MaskChaos: 124,
    },
    DamageclassType: {
        Physical: 0,
        Magical: 1,
    },
    EnvironmentalDamageFlags: {
        OneTime: 1,
        DmgIsPct: 2,
    },
    Environmentaldamagetype: {
        Fatigue: 0,
        Drowning: 1,
        Falling: 2,
        Lava: 3,
        Slime: 4,
        Fire: 5,
    },
    CovenantType: {
        None: 0,
        Kyrian: 1,
        Venthyr: 2,
        NightFae: 3,
        Necrolord: 4,
    },
    FollowerAbilityCastResult: {
        Success: 0,
        Failure: 1,
        NoPendingCast: 2,
        InvalidTarget: 3,
        InvalidFollowerSpell: 4,
        RerollNotAllowed: 5,
        SingleMissionDuration: 6,
        MustTargetFollower: 7,
        MustTargetTrait: 8,
        InvalidFollowerType: 9,
        MustBeUnique: 10,
        CannotTargetLimitedUseFollower: 11,
        MustTargetLimitedUseFollower: 12,
        AlreadyAtMaxDurability: 13,
        CannotTargetNonAutoMissionFollower: 14,
    },
    GarrAutoBoardIndex: {
        None: -1,
        AllyLeftBack: 0,
        AllyRightBack: 1,
        AllyLeftFront: 2,
        AllyCenterFront: 3,
        AllyRightFront: 4,
        EnemyLeftFront: 5,
        EnemyCenterLeftFront: 6,
        EnemyCenterRightFront: 7,
        EnemyRightFront: 8,
        EnemyLeftBack: 9,
        EnemyCenterLeftBack: 10,
        EnemyCenterRightBack: 11,
        EnemyRightBack: 12,
    },
    GarrAutoCombatSpellTutorialFlag: {
        None: 0,
        Single: 1,
        Column: 2,
        Row: 3,
        All: 4,
    },
    GarrAutoCombatTutorial: {
        SelectMission: 1,
        PlaceCompanion: 2,
        HealCompanion: 4,
        LevelHeal: 8,
        BeneficialEffect: 16,
        AttackSingle: 32,
        AttackColumn: 64,
        AttackRow: 128,
        AttackAll: 256,
        TroopTutorial: 512,
        EnvironmentalEffect: 1024,
    },
    GarrAutoCombatantRole: {
        None: 0,
        Melee: 1,
        RangedPhysical: 2,
        RangedMagic: 3,
        HealSupport: 4,
        Tank: 5,
    },
    GarrAutoEventFlags: {
        None: 0,
        AutoAttack: 1,
        Passive: 2,
        Environment: 4,
    },
    GarrAutoMissionEventType: {
        MeleeDamage: 0,
        RangeDamage: 1,
        SpellMeleeDamage: 2,
        SpellRangeDamage: 3,
        Heal: 4,
        PeriodicDamage: 5,
        PeriodicHeal: 6,
        ApplyAura: 7,
        RemoveAura: 8,
        Died: 9,
    },
    GarrAutoPreviewTargetType: {
        None: 0,
        Damage: 1,
        Heal: 2,
        Buff: 4,
        Debuff: 8,
    },
    GarrFollowerMissionCompleteState: {
        Alive: 0,
        KilledByMissionFailure: 1,
        SavedByPreventDeath: 2,
        OutOfDurability: 3,
    },
    GarrFollowerQuality: {
        Common: 1,
        Uncommon: 2,
        Rare: 3,
        Epic: 4,
        Legendary: 5,
        Title: 6,
    },
    GarrTalentCostType: {
        Initial: 0,
        Respec: 1,
        MakePermanent: 2,
        TreeReset: 3,
    },
    GarrTalentFeatureSubtype: {
        Generic: 0,
        Bastion: 1,
        Revendreth: 2,
        Ardenweald: 3,
        Maldraxxus: 4,
    },
    GarrTalentFeatureType: {
        Generic: 0,
        AnimaDiversion: 1,
        TravelPortals: 2,
        Adventures: 3,
        ReservoirUpgrades: 4,
        SanctumUnique: 5,
        SoulBinds: 6,
        AnimaDiversionMap: 7,
    },
    GarrTalentResearchCostSource: {
        Talent: 0,
        Tree: 1,
    },
    GarrTalentSocketType: {
        None: 0,
        Spell: 1,
        Conduit: 2,
    },
    GarrTalentTreeType: {
        Tiers: 0,
        Classic: 1,
    },
    GarrTalentType: {
        Standard: 0,
        Minor: 1,
        Major: 2,
        Socket: 3,
    },
    GarrTalentUI: {
        Generic: 0,
        CovenantSanctum: 1,
        SoulBinds: 2,
        AnimaDiversionMap: 3,
    },
    GarrisonFollowerType: {
        FollowerType_6_0: 1,
        FollowerType_6_2: 2,
        FollowerType_7_0: 4,
        FollowerType_8_0: 22,
        FollowerType_9_0: 123,
    },
    GarrisonTalentAvailability: {
        Available: 0,
        Unavailable: 1,
        UnavailableAnotherIsResearching: 2,
        UnavailableNotEnoughResources: 3,
        UnavailableNotEnoughGold: 4,
        UnavailableTierUnavailable: 5,
        UnavailablePlayerCondition: 6,
        UnavailableAlreadyHave: 7,
        UnavailableRequiresPrerequisiteTalent: 8,
    },
    GarrisonType: {
        Type_6_0: 2,
        Type_7_0: 3,
        Type_8_0: 9,
        Type_9_0: 111,
    },
    InventoryType: {
        IndexNonEquipType: 0,
        IndexHeadType: 1,
        IndexNeckType: 2,
        IndexShoulderType: 3,
        IndexBodyType: 4,
        IndexChestType: 5,
        IndexWaistType: 6,
        IndexLegsType: 7,
        IndexFeetType: 8,
        IndexWristType: 9,
        IndexHandType: 10,
        IndexFingerType: 11,
        IndexTrinketType: 12,
        IndexWeaponType: 13,
        IndexShieldType: 14,
        IndexRangedType: 15,
        IndexCloakType: 16,
        Index2HweaponType: 17,
        IndexBagType: 18,
        IndexTabardType: 19,
        IndexRobeType: 20,
        IndexWeaponmainhandType: 21,
        IndexWeaponoffhandType: 22,
        IndexHoldableType: 23,
        IndexAmmoType: 24,
        IndexThrownType: 25,
        IndexRangedrightType: 26,
        IndexQuiverType: 27,
        IndexRelicType: 28,
    },
    ItemQuality: {
        Poor: 0,
        Common: 1,
        Uncommon: 2,
        Rare: 3,
        Epic: 4,
        Legendary: 5,
        Artifact: 6,
        Heirloom: 7,
        WoWToken: 8,
    },
    RuneforgePowerState: {
        Available: 0,
        Unavailable: 1,
        Invalid: 2,
    },
    PlayerMentorshipApplicationResult: {
        Success: 0,
        AlreadyMentor: 1,
        Ineligible: 2,
    },
    PlayerMentorshipStatus: {
        None: 0,
        Newcomer: 1,
        Mentor: 2,
    },
    QuestTagType: {
        Tag: 0,
        Profession: 1,
        Normal: 2,
        PvP: 3,
        PetBattle: 4,
        Bounty: 5,
        Dungeon: 6,
        Invasion: 7,
        Raid: 8,
        Contribution: 9,
        RatedReward: 10,
        InvasionWrapper: 11,
        FactionAssault: 12,
        Islands: 13,
        Threat: 14,
        CovenantCalling: 15,
    },
    RelativeContentDifficulty: {
        Trivial: 0,
        Easy: 1,
        Fair: 2,
        Difficult: 3,
        Impossible: 4,
    },
    QuestSessionCommand: {
        None: 0,
        Start: 1,
        Stop: 2,
        SessionActiveNoCommand: 3,
    },
    QuestSessionResult: {
        Ok: 0,
        NotInParty: 1,
        InvalidOwner: 2,
        AlreadyActive: 3,
        NotActive: 4,
        InRaid: 5,
        OwnerRefused: 6,
        Timeout: 7,
        Disabled: 8,
        Started: 9,
        Stopped: 10,
        Joined: 11,
        Left: 12,
        OwnerLeft: 13,
        ReadyCheckFailed: 14,
        PartyDestroyed: 15,
        MemberTimeout: 16,
        AlreadyMember: 17,
        NotOwner: 18,
        AlreadyOwner: 19,
        AlreadyJoined: 20,
        NotMember: 21,
        Busy: 22,
        JoinRejected: 23,
        Logout: 24,
        Empty: 25,
        QuestNotCompleted: 26,
        Resync: 27,
        Restricted: 28,
        InPetBattle: 29,
        InvalidPublicParty: 30,
        Unknown: 31,
        InCombat: 32,
    },
    RafLinkType: {
        None: 0,
        Recruit: 1,
        Friend: 2,
        Both: 3,
    },
    SoulbindConduitType: {
        Finesse: 0,
        Potency: 1,
        Endurance: 2,
        Flex: 3,
    },
    SuperTrackingType: {
        Quest: 0,
        UserWaypoint: 1,
        Corpse: 2,
        Scenario: 3,
    },
    UIWidgetLayoutDirection: {
        Default: 0,
        Vertical: 1,
        Horizontal: 2,
        Overlap: 3,
        HorizontalForceNewRow: 4,
    },
    UIWidgetScale: {
        OneHundred: 0,
        Ninty: 1,
        Eighty: 2,
        Seventy: 3,
        Sixty: 4,
        Fifty: 5,
    },
    UIWidgetSetLayoutDirection: {
        Vertical: 0,
        Horizontal: 1,
    },
    UIWidgetVisualizationType: {
        IconAndText: 0,
        CaptureBar: 1,
        StatusBar: 2,
        DoubleStatusBar: 3,
        IconTextAndBackground: 4,
        DoubleIconAndText: 5,
        StackedResourceTracker: 6,
        IconTextAndCurrencies: 7,
        TextWithState: 8,
        HorizontalCurrencies: 9,
        BulletTextList: 10,
        ScenarioHeaderCurrenciesAndBackground: 11,
        TextureAndText: 12,
        SpellDisplay: 13,
        DoubleStateIconRow: 14,
        TextureAndTextRow: 15,
        ZoneControl: 16,
        CaptureZone: 17,
        TextureWithAnimation: 18,
        DiscreteProgressSteps: 19,
        ScenarioHeaderTimer: 20,
    },
};
